name: Deploy Resume to Self-Hosted Server

on:
  push:
    branches: [main]  # or your deployment branch

jobs:
  build-and-deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Stop old container
        run: |
          docker stop portfolio-container || true
          docker rm portfolio-container || true

      - name: Build Docker image
        run: |
          docker build -t portfolio-app .

      - name: Run new container on port 1707
        run: |
          docker run -d --name portfolio-container -p 1707:80 portfolio-app
