name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Build Docker Image
        run: |
          docker build -t portfolio-app:latest -f docker/Dockerfile .

      - name: Stop and Remove Existing Container (if running)
        run: |
          docker stop portfolio-container || true
          docker rm portfolio-container || true

      - name: Run New Container
        run: |
          docker run -d \
            --name portfolio-container \
            -p 1707:80 \
            portfolio-app:latest

